// Code generated by gobind. DO NOT EDIT.

// Java class mobile.Mobile is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java mobile
package mobile;

import go.Seq;

public abstract class Mobile {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Mobile() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	/**
	 * AddNumbers tests basic computation
	 */
	public static native long addNumbers(long a, long b);
	/**
	 * MinimalTest provides the absolute minimum test without any dependencies
	 */
	public static native String minimalTest();
	/**
	 * NewRelayMobileAPI creates a new Relay Mobile API instance
	 */
	public static native RelayMobileAPI newRelayMobileAPI();
}
