// Code generated by gobind. DO NOT EDIT.

// Java class mobile.RelayMobileAPI is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java mobile
package mobile;

import go.Seq;

/**
 * RelayMobileAPI provides Relay functionality for mobile clients
 */
public final class RelayMobileAPI implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	/**
	 * NewRelayMobileAPI creates a new Relay Mobile API instance
	 */
	public RelayMobileAPI() {
		this.refnum = __NewRelayMobileAPI();
		Seq.trackGoRef(refnum, this);
	}
	
	private static native int __NewRelayMobileAPI();
	
	RelayMobileAPI(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	/**
	 * CreateAccount creates a new Relay account using cmd package functionality
	 */
	public native String createAccount(String nickname) throws Exception;
	/**
	 * GetAccountByNickname returns account information by nickname
	 */
	public native String getAccountByNickname(String nickname) throws Exception;
	/**
	 * GetAccountInfo returns basic account information
	 */
	public native String getAccountInfo(String accountID) throws Exception;
	/**
	 * GetDataDirectory returns the current data directory
	 */
	public native String getDataDirectory();
	/**
	 * Initialize sets up the mobile API with a data directory
	 */
	public native void initialize(String dataDir) throws Exception;
	/**
	 * IsInitialized returns whether the API has been initialized
	 */
	public native boolean isInitialized();
	/**
	 * ListAccounts returns a list of available accounts using cmd package functionality
	 */
	public native String listAccounts() throws Exception;
	/**
	 * SendFile sends a file using cmd package functionality
	 */
	public native String sendFile(String fromAccountID, String toAccountID, String filePath) throws Exception;
	/**
	 * SendTextMessage sends a text message using cmd package functionality
	 */
	public native String sendTextMessage(String fromAccountID, String toAccountID, String message) throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof RelayMobileAPI)) {
		    return false;
		}
		RelayMobileAPI that = (RelayMobileAPI)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("RelayMobileAPI").append("{");
		return b.append("}").toString();
	}
}

